[2023-06-12 01:40:59,460] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tercera_entrega_ecentoz.db_connect scheduled__2023-05-30T00:00:00+00:00 [queued]>
[2023-06-12 01:40:59,475] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tercera_entrega_ecentoz.db_connect scheduled__2023-05-30T00:00:00+00:00 [queued]>
[2023-06-12 01:40:59,478] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-12 01:40:59,481] {taskinstance.py:1377} INFO - Starting attempt 5 of 6
[2023-06-12 01:40:59,482] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-12 01:40:59,527] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): db_connect> on 2023-05-30 00:00:00+00:00
[2023-06-12 01:40:59,562] {standard_task_runner.py:52} INFO - Started process 210 to run task
[2023-06-12 01:40:59,575] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tercera_entrega_ecentoz', 'db_connect', 'scheduled__2023-05-30T00:00:00+00:00', '--job-id', '354', '--raw', '--subdir', 'DAGS_FOLDER/dag_tercera_entrega.py', '--cfg-path', '/tmp/tmplzwawgpj', '--error-file', '/tmp/tmp20j7ux0j']
[2023-06-12 01:40:59,588] {standard_task_runner.py:80} INFO - Job 354: Subtask db_connect
[2023-06-12 01:40:59,746] {standard_task_runner.py:97} ERROR - Failed to execute job 354 for task db_connect ((psycopg2.OperationalError) terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

(Background on this error at: https://sqlalche.me/e/14/e3q8); 210)
[2023-06-12 01:40:59,872] {local_task_job.py:156} INFO - Task exited with return code 1
