[2023-06-12 01:40:59,499] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tercera_entrega_ecentoz.db_connect scheduled__2023-06-10T00:00:00+00:00 [queued]>
[2023-06-12 01:40:59,574] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tercera_entrega_ecentoz.db_connect scheduled__2023-06-10T00:00:00+00:00 [queued]>
[2023-06-12 01:40:59,584] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-12 01:40:59,589] {taskinstance.py:1377} INFO - Starting attempt 5 of 6
[2023-06-12 01:40:59,590] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-12 01:40:59,690] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): db_connect> on 2023-06-10 00:00:00+00:00
[2023-06-12 01:40:59,711] {standard_task_runner.py:52} INFO - Started process 217 to run task
[2023-06-12 01:40:59,761] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tercera_entrega_ecentoz', 'db_connect', 'scheduled__2023-06-10T00:00:00+00:00', '--job-id', '345', '--raw', '--subdir', 'DAGS_FOLDER/dag_tercera_entrega.py', '--cfg-path', '/tmp/tmp9j21ksnf', '--error-file', '/tmp/tmpcsqof70t']
[2023-06-12 01:40:59,771] {standard_task_runner.py:80} INFO - Job 345: Subtask db_connect
[2023-06-12 01:40:59,909] {cli_action_loggers.py:105} WARNING - Failed to log action with (psycopg2.OperationalError) connection to server at "postgres" (172.19.0.2), port 5432 failed: FATAL:  the database system is shutting down

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-06-12 01:40:59,961] {standard_task_runner.py:97} ERROR - Failed to execute job 345 for task db_connect ((psycopg2.OperationalError) connection to server at "postgres" (172.19.0.2), port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

(Background on this error at: https://sqlalche.me/e/14/e3q8); 217)
[2023-06-12 01:41:00,011] {local_task_job.py:156} INFO - Task exited with return code 1
